apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: mcp-demo
  labels:
    app: mcp-server
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: mcp-server
